name: Project aligned task 1

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run pipeline in different env'
        type: choice
        default: 'dev'
        required: true
        options:
        - dev
        - stage
        - qa
        - prod

env:
  CFN_S3_FILE_PATH: ${{inputs.environment}}-s3-path
  APP_NAME: ${{inputs.environment}}-app
  SERVICE_NAME: ${{inputs.environment}}-service
  CFN_PARAMS_PATH: ${{inputs.environment}}-param-path

jobs:
  job1:
    name: Setup Env Variables
    runs-on: ubuntu-latest
    steps:
      - name: Getting code
        uses: actions/checkout@v4
      - name: Setting up environment variables
        run: |
          echo "CFN_S3_FILE_PATH=${CFN_S3_FILE_PATH}" >> $GITHUB_ENV
          echo "APP_NAME=${APP_NAME}" >> $GITHUB_ENV
          echo "SERVICE_NAME=${SERVICE_NAME}" >> $GITHUB_ENV
          echo "CFN_PARAMS_PATH=${CFN_PARAMS_PATH}" >> $GITHUB_ENV
